baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Autorize'
theme = 'terminal'
paginate = 5

[params]
    contentTypeName = "posts"
    themeColor = "blue"
    showLanguageSelector = false
    fullWidthTheme = false
    showMenuItems = 2
    centerTheme = true
    autoCover = true
    favicon = "favicon.png"


[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Autorize"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"  
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"